name: Build Shabanas Budget Tracker APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - name: 🚀 Maximize Build Space
        uses: gmij/max-build-space@v0.4
        with:
          root-reserve-mb: 512
          temp-reserve-mb: 100
          swap-size-mb: 1024
          remove-android: 'false'
          remove-haskell: 'true'
          remove-docker-images: 'true'
          remove-codeql: 'true'
          remove-large-packages: 'true'
          remove-tool-cache: 'true'
          remove-dotnet: 'true'

      - name: 💾 Check available space
        run: |
          echo "===== DISK SPACE ====="
          df -h
          echo "======================"

      - name: 📦 Checkout
        uses: actions/checkout@v4

      - name: 📱 Build Android APK
        uses: love-actions/love-actions-android@v2
        with:
          app-name: "Shabanas Budget Tracker"
          bundle-id: "com.mano.shabanabudgettracker"
          love-ref: "11.5"
          love-package: "./game.love"
          product-name: "ShabanasBudgetTracker"
          version-string: "1.0.0"
          version-code: 1
          output-folder: "./build"

      - name: 📤 Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Shabanas-Budget-Tracker-APK
          path: "./build/*.apk"
